package io.acionyx.tunguska.app

object UiTags {
    const val MAIN_SCROLL_COLUMN = "main_scroll_column"
    const val IMPORT_DRAFT_FIELD = "import_draft_field"
    const val VALIDATE_IMPORT_BUTTON = "validate_import_button"
    const val OPEN_CAMERA_BUTTON = "open_camera_button"
    const val SCAN_IMAGE_BUTTON = "scan_image_button"
    const val CONFIRM_IMPORT_BUTTON = "confirm_import_button"
    const val DISCARD_IMPORT_BUTTON = "discard_import_button"
    const val CONNECT_BUTTON = "connect_button"
    const val STOP_BUTTON = "stop_button"
    const val REFRESH_RUNTIME_BUTTON = "refresh_runtime_button"
    const val RESTAGE_RUNTIME_BUTTON = "restage_runtime_button"
    const val SHOW_DIAGNOSTICS_BUTTON = "show_diagnostics_button"
    const val RUSSIA_DIRECT_SWITCH = "russia_direct_switch"
    const val CONFIGURE_REGIONAL_BYPASS_BUTTON = "configure_regional_bypass_button"
    const val ADD_DIRECT_DOMAIN_BUTTON = "add_direct_domain_button"
    const val ACCEPT_RUSSIA_DIRECT_PROMPT_BUTTON = "accept_russia_direct_prompt_button"
    const val DECLINE_RUSSIA_DIRECT_PROMPT_BUTTON = "decline_russia_direct_prompt_button"
    const val AUTOMATION_ENABLE_SWITCH = "automation_enable_switch"
    const val AUTOMATION_ROTATE_TOKEN_BUTTON = "automation_rotate_token_button"
    const val AUTOMATION_COPY_TOKEN_BUTTON = "automation_copy_token_button"
    const val AUTOMATION_REFRESH_BUTTON = "automation_refresh_button"
}
